// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLHydHK47JFGnbuOreF-2T4lOK7YFnx_A',
    appId: '1:893259397520:android:81c4311d3642d7177bdb15',
    messagingSenderId: '893259397520',
    projectId: 'fooddeliverytute-77013',
    storageBucket: 'fooddeliverytute-77013.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ3EoJ2DjYxYqLEbrWXeq7tdqamiOUZdQ',
    appId: '1:893259397520:ios:0aaa3752ee2889587bdb15',
    messagingSenderId: '893259397520',
    projectId: 'fooddeliverytute-77013',
    storageBucket: 'fooddeliverytute-77013.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgNF21es64S4MwfnCgqLKDvNg6pCn09Io',
    appId: '1:893259397520:web:e8d777b4d66666d87bdb15',
    messagingSenderId: '893259397520',
    projectId: 'fooddeliverytute-77013',
    authDomain: 'fooddeliverytute-77013.firebaseapp.com',
    storageBucket: 'fooddeliverytute-77013.firebasestorage.app',
    measurementId: 'G-6FP6XL5NDV',
  );

}